#!/usr/bin/R --vanilla
install.packages('lattice', repos="http://cran.rstudio.com/")
install.packages('Rcpp', repos="http://cran.rstudio.com/")
install.packages('RcppArmadillo', repos="http://cran.rstudio.com/")
install.packages('zoo', repos="http://cran.rstudio.com/")
install.packages('abind', repos="http://cran.rstudio.com/")
install.packages('reshape2', repos="http://cran.rstudio.com/")
install.packages('ggplot2', repos="http://cran.rstudio.com/")
install.packages('neuralnet', repos="http://cran.rstudio.com/")
