#!/usr/bin/env bash
export R_CUSTOM=$1 
shift 1
args=
for var in "$@"; do
    args=$args" "$var    
done
if [ -z "$args" ]; then
    /usr/bin/R -q --no-save
else    
    file=$R_CUSTOM
    R_CUSTOM=
    /usr/bin/R -q --no-save -f $file --args $args
fi
