# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

probFun <- function(u, c) {
    .Call('snn_probFun', PACKAGE = 'snn', u, c)
}

kernelWindow <- function(d, kernel_options) {
    .Call('snn_kernelWindow', PACKAGE = 'snn', d, kernel_options)
}

kernelCorrMat <- function(d, kernel_options) {
    .Call('snn_kernelCorrMat', PACKAGE = 'snn', d, kernel_options)
}

kernelCrossCorrMat <- function(d1, d2, kernel_options) {
    .Call('snn_kernelCrossCorrMat', PACKAGE = 'snn', d1, d2, kernel_options)
}

kernelCrossCorr <- function(d1, d2, kernel_options) {
    .Call('snn_kernelCrossCorr', PACKAGE = 'snn', d1, d2, kernel_options)
}

kernelCrossEntropy <- function(d1, d2, kernel_options) {
    .Call('snn_kernelCrossEntropy', PACKAGE = 'snn', d1, d2, kernel_options)
}

