// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// setVerboseLevel
void setVerboseLevel(int level);
RcppExport SEXP Rdnn_setVerboseLevel(SEXP levelSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type level(levelSEXP);
    setVerboseLevel(level);
    return R_NilValue;
END_RCPP
}
// chopTimeSeries
Rcpp::List chopTimeSeries(Rcpp::List l);
RcppExport SEXP Rdnn_chopTimeSeries(SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type l(lSEXP);
    __result = Rcpp::wrap(chopTimeSeries(l));
    return __result;
END_RCPP
}
// chopSpikesList
Rcpp::List chopSpikesList(Rcpp::List l);
RcppExport SEXP Rdnn_chopSpikesList(SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type l(lSEXP);
    __result = Rcpp::wrap(chopSpikesList(l));
    return __result;
END_RCPP
}
