# This file was *autogenerated* from the file ././kempter.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_40 = Integer(40); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_100 = Integer(100); _sage_const_10 = Integer(10); _sage_const_1000 = Integer(1000); _sage_const_1p0475 = RealNumber('1.0475')#!/usr/bin/env sage
v0 = _sage_const_0 
N = _sage_const_100 
M1 = N/_sage_const_2 
M2 = N/_sage_const_2 
nu = _sage_const_10 **-_sage_const_5 
w_in = nu
w_out = -_sage_const_1p0475 *nu
mu_in = _sage_const_10 

t0 = _sage_const_10 

var('t', 's')

# epsp ==================================
__tmp__=var("t"); epsp_full = symbolic_expression((t/(t0**_sage_const_2 ))*exp(-t/t0)).function(t)
__tmp__=var("t"); func_null = symbolic_expression(_sage_const_0 ).function(t)
epsp = Piecewise([ [(-infinity, _sage_const_0 ), func_null], [(_sage_const_0 , infinity), epsp_full] ])
# W =====================================
t_syn = _sage_const_5  # ms
t_pos = _sage_const_1  # ms
t_neg = _sage_const_10  # ms
Apos = _sage_const_1 
Aneg = -_sage_const_1 
t_pos_ = t_syn*t_pos/(t_syn+t_pos)
t_neg_ = t_syn*t_neg/(t_syn+t_neg)

W_ltp = exp(t/t_syn)*(Apos*(_sage_const_1 -t/t_pos_) + Aneg*(_sage_const_1 -t/t_neg_))
W_ltd = Apos*exp(-t/t_pos) + Aneg*exp(-t/t_neg)
W = Piecewise([ [(-_sage_const_1000 ,_sage_const_0 ), W_ltp ],
                [(_sage_const_0 , _sage_const_1000 ), W_ltd ],
              ])

plot(W, t, _sage_const_1 ,_sage_const_10 )
# lambda ===============================================
__tmp__=var("t"); lambda_in = symbolic_expression(mu_in*cos(t/_sage_const_1000 *_sage_const_2 *_sage_const_40 *_sage_const_2 *pi) + mu_in).function(t)
#lambda_in(t) = 10

epsp_l = epsp.laplace(t, s)
lambda_in_l = lambda_in.laplace(t, s)

lambda_big = inverse_laplace( epsp_l*lambda_in_l, s, t)


#print integrate(lambda_big, -infinity, infinity)
