// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// testFun
List testFun(List d1, List d2);
RcppExport SEXP Rsnn_testFun(SEXP d1SEXP, SEXP d2SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< List >::type d1(d1SEXP );
        Rcpp::traits::input_parameter< List >::type d2(d2SEXP );
        List __result = testFun(d1, d2);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
