// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// integrateSRM
SEXP integrateSRM(const List constants, const List int_options, const IntegerVector neuron_id, const IntegerVector neuron_id_conn, const NumericVector neuron_w, const List net);
RcppExport SEXP snnSRM_integrateSRM(SEXP constantsSEXP, SEXP int_optionsSEXP, SEXP neuron_idSEXP, SEXP neuron_id_connSEXP, SEXP neuron_wSEXP, SEXP netSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const List >::type constants(constantsSEXP );
        Rcpp::traits::input_parameter< const List >::type int_options(int_optionsSEXP );
        Rcpp::traits::input_parameter< const IntegerVector >::type neuron_id(neuron_idSEXP );
        Rcpp::traits::input_parameter< const IntegerVector >::type neuron_id_conn(neuron_id_connSEXP );
        Rcpp::traits::input_parameter< const NumericVector >::type neuron_w(neuron_wSEXP );
        Rcpp::traits::input_parameter< const List >::type net(netSEXP );
        SEXP __result = integrateSRM(constants, int_options, neuron_id, neuron_id_conn, neuron_w, net);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// USRM
SEXP USRM(const NumericVector t, const List constants, const IntegerVector neuron_id, const IntegerVector neuron_id_conn, const NumericVector neuron_w, const List net);
RcppExport SEXP snnSRM_USRM(SEXP tSEXP, SEXP constantsSEXP, SEXP neuron_idSEXP, SEXP neuron_id_connSEXP, SEXP neuron_wSEXP, SEXP netSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const NumericVector >::type t(tSEXP );
        Rcpp::traits::input_parameter< const List >::type constants(constantsSEXP );
        Rcpp::traits::input_parameter< const IntegerVector >::type neuron_id(neuron_idSEXP );
        Rcpp::traits::input_parameter< const IntegerVector >::type neuron_id_conn(neuron_id_connSEXP );
        Rcpp::traits::input_parameter< const NumericVector >::type neuron_w(neuron_wSEXP );
        Rcpp::traits::input_parameter< const List >::type net(netSEXP );
        SEXP __result = USRM(t, constants, neuron_id, neuron_id_conn, neuron_w, net);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP snnSRM_rcpp_hello_world() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        List __result = rcpp_hello_world();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
