# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

integrateSRM <- function(constants, int_options, neuron_id, neuron_id_conn, neuron_w, net) {
    .Call('snnSRM_integrateSRM', PACKAGE = 'snnSRM', constants, int_options, neuron_id, neuron_id_conn, neuron_w, net)
}

USRM <- function(t, constants, neuron_id, neuron_id_conn, neuron_w, net) {
    .Call('snnSRM_USRM', PACKAGE = 'snnSRM', t, constants, neuron_id, neuron_id_conn, neuron_w, net)
}

USRMs <- function(t, constants, neurons_id, neurons_id_conn, neurons_w, net) {
    .Call('snnSRM_USRMs', PACKAGE = 'snnSRM', t, constants, neurons_id, neurons_id_conn, neurons_w, net)
}

