# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

integrateSRM <- function(constants, int_options, neuron_id, neuron_id_conn, neuron_w, net) {
    .Call('snnSRM_integrateSRM', PACKAGE = 'snnSRM', constants, int_options, neuron_id, neuron_id_conn, neuron_w, net)
}

USRM <- function(t, constants, neuron_id, neuron_id_conn, neuron_w, net) {
    .Call('snnSRM_USRM', PACKAGE = 'snnSRM', t, constants, neuron_id, neuron_id_conn, neuron_w, net)
}

rcpp_hello_world <- function() {
    .Call('snnSRM_rcpp_hello_world', PACKAGE = 'snnSRM')
}

