require(snn)
require(snowfall)
require(cubature)

source('util.R')
source('neuron.R')
source('gen_spikes.R')
source('plot_funcs.R')
source('grad_funcs.R')
source('llh.R')
source('srm.R')
source('serialize_to_bin.R')
source('learn_and_run_net.R')
source('target_functions.R')
source('softmax.R')