# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

evalNet <- function(patterns, run_options, constants, layers) {
    .Call('snn_evalNet', PACKAGE = 'snn', patterns, run_options, constants, layers)
}

integrateSRM <- function(constants, int_options, neuron_id, neuron_id_conn, neuron_w, net) {
    .Call('snn_integrateSRM', PACKAGE = 'snn', constants, int_options, neuron_id, neuron_id_conn, neuron_w, net)
}

integrateSRM_epsp_pstroke <- function(constants, int_options, neurons_id, neurons_id_conn, neurons_w, net) {
    .Call('snn_integrateSRM_epsp_pstroke', PACKAGE = 'snn', constants, int_options, neurons_id, neurons_id_conn, neurons_w, net)
}

probNoFire <- function(T0, Tmax, neurons, net, constants) {
    .Call('snn_probNoFire', PACKAGE = 'snn', T0, Tmax, neurons, net, constants)
}

probInt <- function(T0, Tmax, neurons, net, constants) {
    .Call('snn_probInt', PACKAGE = 'snn', T0, Tmax, neurons, net, constants)
}

integrateSRM_epsp <- function(neurons, int_options, net, constants) {
    .Call('snn_integrateSRM_epsp', PACKAGE = 'snn', neurons, int_options, net, constants)
}

test_binary_search <- function(t, y) {
    .Call('snn_test_binary_search', PACKAGE = 'snn', t, y)
}

neuron_epsp <- function(t, constants, neuron_id, neuron_id_conn, neuron_w, net) {
    .Call('snn_neuron_epsp', PACKAGE = 'snn', t, constants, neuron_id, neuron_id_conn, neuron_w, net)
}

USRM <- function(t, constants, neuron_id, neuron_id_conn, neuron_w, net) {
    .Call('snn_USRM', PACKAGE = 'snn', t, constants, neuron_id, neuron_id_conn, neuron_w, net)
}

USRMs <- function(t, constants, neurons_id, neurons_id_conn, neurons_w, net) {
    .Call('snn_USRMs', PACKAGE = 'snn', t, constants, neurons_id, neurons_id_conn, neurons_w, net)
}

USRMsFull <- function(t, constants, neurons_id, neurons_id_conn, neurons_w, net) {
    .Call('snn_USRMsFull', PACKAGE = 'snn', t, constants, neurons_id, neurons_id_conn, neurons_w, net)
}

kernelWindow_spikes <- function(d, kernel_options) {
    .Call('snn_kernelWindow_spikes', PACKAGE = 'snn', d, kernel_options)
}

kernelPass_autoCorr <- function(d, kernel_options) {
    .Call('snn_kernelPass_autoCorr', PACKAGE = 'snn', d, kernel_options)
}

kernelPass_corr <- function(d1, d2, kernel_options) {
    .Call('snn_kernelPass_corr', PACKAGE = 'snn', d1, d2, kernel_options)
}

kernelPass_crossNeurons <- function(d1, d2, kernel_options) {
    .Call('snn_kernelPass_crossNeurons', PACKAGE = 'snn', d1, d2, kernel_options)
}

simLayers <- function(sim_options, constants, layers, net) {
    .Call('snn_simLayers', PACKAGE = 'snn', sim_options, constants, layers, net)
}

simLayers_old <- function(sim_options, constants, layers, net) {
    .Call('snn_simLayers_old', PACKAGE = 'snn', sim_options, constants, layers, net)
}

generateCorrPoiss <- function(M, r, corr, T0, Tmax, dt, tauc) {
    .Call('snn_generateCorrPoiss', PACKAGE = 'snn', M, r, corr, T0, Tmax, dt, tauc)
}

timesTwo <- function(x) {
    .Call('snn_timesTwo', PACKAGE = 'snn', x)
}

